### ISSUE TITLE
Mapping Volumes to Local Disk for SimpleRisk docker - Breaks functionality

### ISSUE THREAD

**Issue by jemcgrath1** [simplerisk/docker#1]
Mapping the 6 volumes to local disk (so that the config and database is stored outside of the docker container) breaks the simplerisk container.

Please advise

**Comment by jsokol** [comment]
Hello.  This is correct.  The docker image provided does not map volumes externally.  We do not have instructions on how to do this, nor do we consider ourselves to be docker experts.  If you do figure out how to make this work, please let us know, and we'd be happy to adjust the image accordingly.

**Comment by Tom-Davidson** [comment]
This should be fixed by #3

**Comment by jsokol** [comment]
This should be fixed with the new Docker code.
