### ISSUE TITLE
Publish simplerisk-minimal Docker image to Docker Hub

### ISSUE THREAD

**Issue by elyscape** [simplerisk/docker#11]
The `simplerisk` image is published to [a repository on Docker Hub][simplerisk]. The `simplerisk-minimal` image, however, [has a repository on Docker Hub][simplerisk-minimal] but is not published to it. Please publish this image as well.

[simplerisk]: https://hub.docker.com/r/simplerisk/simplerisk
[simplerisk-minimal]: https://hub.docker.com/r/simplerisk/simplerisk-minimal

**Comment by WolfangAukang** [comment]
Thank you for reaching out @elyscape. Sure, I will let you know when it is done

**Comment by WolfangAukang** [comment]
Ready, I have published the image on the official Docker Hub repo. For now it only has the latest tag, which uses PHP 7.2. I will try to push the version with PHP 7.4 throughout the day. Let me know if you have any other concerns.

**Comment by WolfangAukang** [comment]
Done, the following tags are currently available:
- latest
- 20210305-001
- 20210305-001-php72
- 20210305-001-php74

**Comment by jsokol** [comment]
Closing out this issue as the request has been fulfilled.
