### ISSUE TITLE
No releases available for package "pecl.php.net/mcrypt" install failed

### ISSUE THREAD

**Issue by Hotelbravo722** [simplerisk/docker#2]
Was building the 18.04 image and received this error

"No releases available for package "pecl.php.net/mcrypt"
install failed"

Mcrypt has been depreciated and was wondering if its a dependent module or if I can use something else.

**Comment by jsokol** [comment]
MCrypt is only needed for customers who were using the old version of our Encrypted Database Extra and it was only necessary while those customers moved over to OpenSSL Encryption.  You should be able to comment out that line without any impact.  Is this from building the Docker image?

**Comment by Hotelbravo722** [comment]
Yes

**Comment by jsokol** [comment]
Strange.  I tried to run the 18.04 docker image and it completed successfully without that error.  Not sure what's up with that.

**Comment by jsokol** [comment]
This should no longer be an issue with the new docker files.
