### ISSUE TITLE
Image is incompatible with deployment to Kubernetes

### ISSUE THREAD

**Issue by mark-webster-catalyst** [simplerisk/docker#45]
Kubernetes Ingress expects TLS to terminate at the ingress controller, all communication from that point on is plaintext (port 80). The rewrite rule included in the `common/000-default.conf` files causes a redirect loop when deployed to a kubernetes cluster with an ingress controller.

**Comment by jsokol** [comment]
Hey Mark.  Thanks for letting us know.  While I hear what you're saying, the flip side of this is that the vast majority of those using Docker containers are not using an ingress controller and would expect HTTPS to work through to the Apache web service.  I'm no expert on Ingress, but a quick Google search did turn up that it can route traffic to a HTTPS service on the backend.  Please take a look at this and see if it makes sense to you.

[https://stackoverflow.com/questions/46800404/kubernetes-ingress-how-to-enable-https-to-backend-service](https://stackoverflow.com/questions/46800404/kubernetes-ingress-how-to-enable-https-to-backend-service)

**Comment by WolfangAukang** [comment]
Closing ticket because of no response.

**Comment by jsokol** [comment]
I have successfully run this Docker image on a Kubernetes platform using an ingress nginx controller.  I had no issues with using SSL on it and everything works as I would expect.  Since I have been unable to reproduce this, the issue has been closed.
