### ISSUE TITLE
fpm image variant

### ISSUE THREAD

**Issue by kale1d0code** [simplerisk/docker#84]
reading through the project, I noticed the minimal image variant includes apache.

A version which only provides php-fpm for cgi would be beneficial.

**Comment by jsokol** [comment]
This is correct.  All SimpleRisk deployment models use some form of an *AMP stack.  Our support team is familiar with configuring and supporting Apache, but has no familiarity with php-fpm.  We have no intent to support it at this time.

**Comment by kale1d0code** [comment]
By configuring and supporting Apache your support staff are already familiar with php-fpm

php-fpm is a SAPI. Apache makes requests to php via fast-cgi which is what php-fpm does.

**Comment by jsokol** [comment]
That seems like a large understatement.  If it were the same thing, then it would not require additional modules or configuration.  It is that which you are asking us to support, and we cannot.  We have no intent to support it at this time.
