### ISSUE TITLE
support special characters in passwords

### ISSUE THREAD

**Issue by kale1d0code** [simplerisk/docker#85]
the DB_SETUP_PASS environment variable does not support the '<' character.
using a database password with a '<' symbol causes the following error messsage:

bash: line 1: <REST_OF_PASSWORD_AFTER_SYMBOL>: No such file or directory
Was not able to apply settings on database. Check error above. Exiting.

**Comment by jsokol** [comment]
The entrypoint.sh script is a bash script and the '<' character is a control character in bash.  Other bash control characters such as |, >, and ` would not be allowed, as well.  If you have suggestions for how to modify the script to support this special characters, feel free to submit a PR for it, but we do not have plans to make this change at this time.
