### ISSUE TITLE
unable to start. Expects database to not exist

### ISSUE THREAD

**Issue by kale1d0code** [simplerisk/docker#86]
when setting up simplerisk with mariadb
simplerisk will crash with the message:
Can't create database '<DATABASE_NAME>'; database exists

mariadb container is responsible for creating the database
simplerisk should populate database with tables

**Comment by jsokol** [comment]
It sounds like you're using the "simplerisk" docker, which does include the database creation.  If you are creating the database via another method, or one already exists, then you should use the SimpleRisk Minimal image:

https://github.com/simplerisk/docker/tree/master/simplerisk-minimal

**Comment by kale1d0code** [comment]
I experienced this issue on the minimal variant [simplerisk-minimal](https://github.com/simplerisk/docker/tree/master/simplerisk-minimal) image

**Comment by jsokol** [comment]
We use the simplerisk-minimal image internally with no issues for both the database setup and hosting of the image.  You just need to specify the SIMPLERISK_DB_* options when spinning up the container to tell it how to connect to the existing database.

SIMPLERISK_DB_HOSTNAME
SIMPLERISK_DB_PORT
SIMPLERISK_DB_USERNAME
SIMPLERISK_DB_PASSWORD
SIMPLERISK_DB_DATABASE

If you do not specify these values, it will assume that a "simplerisk" database i s already running on localhost with a user/pass of "simplerisk".
